package com.oasisfeng.nevo.decorators.wechat;

import android.os.Build.VERSION_CODES;
import static android.os.Build.VERSION.SDK_INT;

/**
 * Static map for WeChat Emoji markers
 *
 * Created by Oasis on 2018-8-9.
 */
public class EmojiMap {

	// Pull Request is welcome. (columns are split by "tab" for visual alignment)
	// Proper emoji is needed for commented lines.
	static final String[][] MAP = new String[][] {
			{ "表情",       null,           "㊙️" },
			{ "链接",       null,           "🔗" },
			{ "花",         null,           "🌺" },
			{ "钱",         null,           "💰" },
			{ "闪烁",       null,           "✨" },
			{ "X",          "X",           "❌" },
			{ "OK",			"OK",			"👌" },
			{ "耶",			"Yeah!",		"✌" },
			{ "嘘",			"Silent",		"🤫" },
			{ "晕",			"Dizzy",		"😲" },
			{ "衰",			"BadLuck",		"😳" },
			{ "脸红",		null,      		"😳" },
			{ "色",			"Drool",		"😍" },
			{ "囧",			"Tension",		"☺" },
			{ "热情",		null,   		"☺" },
			{ "鸡",			"Chick",		"🐥" }, // missing
			{ "强",			"Thumbs Up",	"👍" },
			{ "弱",			"Weak",			"👎" },
			{ "睡",			"Sleep",		"😴" }, // missing
			{ "吐",			"Puke",			"🤢" },
			{ "困",			"Drowsy",		"😪" },
			{ "睡觉",		null,   		"😪" },
			{ "發",			"Rich",			"🀅" },
			{ "微笑",		"Smile",		"😃" },
			{ "大笑",		null,   		"😃" }, // iOS 7.0.4
			{ "开心",		null,   		"😃" }, // Android 7.0.4
			{ "撇嘴",		"Grimace",		"😖" },
			{ "呸",		    null,   		"😖" },
			{ "发呆",		"Scowl",		"😳" },
			{ "脸红",		null,   		"😳" },
			{ "得意",		"CoolGuy",		"😎" }, // missing
			{ "流泪",		"Sob",			"😭" },
			{ "哭",		    null,			"😭" },
			{ "害羞",		"Shy",			"☺" },
			{ "闭嘴",		"Shutup",		"🤐" }, // missing
			{ "大哭",		"Cry",			"😣" },
			{ "悔恨",		null,			"😣" },
			{ "尴尬",		"Awkward",		"😰" },
			{ "担心",		null,   		"😰" },
			{ "发怒",		"Angry",		"😡" },
			{ "生气",		null,	    	"😡" },
			{ "调皮",		"Tongue",		"😜" },
			{ "戏弄",		null,   		"😜" },
			{ "呲牙",		"Grin",			"😁" },
			{ "露齿笑",		null,			"😁" },
			{ "惊讶",		"Surprise",		"😱" },
			{ "难过",		"Frown",		"🙁" },
			{ "抓狂",		"Scream",		"😫" },
			{ "偷笑",		"Chuckle",		"😅" },
			{ "愉快",		"Joyful",		"☺" },
			{ "白眼",		"Slight",		"🙄" },
			{ "傲慢",		"Smug",			"😕" },
			{ "惊恐",		"Panic",		"😱" },
			{ "流汗",		"Sweat",		"😓" },
			{ "憨笑",		"Laugh",		"😄" },
			{ "悠闲",		"Loafer",		"😌" },
			{ "奋斗",		"Strive",		"💪" },
			{ "咒骂",		"Scold",		"😤" },
			{ "疑问",		"Doubt",		"❓" },
			{ "骷髅",		"Skull",		"💀" },
			{ "敲打",		"Hammer",		"👊" },
			{ "捂脸",		"Facepalm",		"🤦" },
			{ "奸笑",		"Smirk",		"😏" },
			{ "皱眉",		"Concerned",	"😟" },
			{ "红包",		"Packet",		SDK_INT > VERSION_CODES.O_MR1 ? "🧧"/* Emoji 11+ */: "💰" },
			{ "小狗",		"Pup",			"🐶" },
			{ "再见",		"Bye",			"🙋" },
			{ "擦汗",		"Relief",		"😥" },
			{ "鼓掌",		"Clap",			"👏" },
			{ "坏笑",		"Trick",		"👻" },
			{ "哈欠",		"Yawn",			"😪" },
			{ "鄙视",		"Lookdown",		"😒" },
			{ "委屈",		"Wronged",		"😣" },
			{ "阴险",		"Sly",			"😈" },
			{ "亲亲",		"Kiss",			"😘" },
			{ "菜刀",		"Cleaver",		"🔪" },
			{ "西瓜",		"Melon",		"🍉" },
			{ "啤酒",		"Beer",			"🍺" },
			{ "咖啡",		"Coffee",		"☕" },
			{ "猪头",		"Pig",			"🐷" },
			{ "玫瑰",		"Rose",			"🌹" },
			{ "凋谢",		"Wilt",			"🥀" },
			{ "嘴唇",		"Lip",			"💋" },
			{ "爱心",		"Heart",		"❤" },
			{ "心碎",		"BrokenHeart",	"💔" },
			{ "蛋糕",		"Cake",			"🎂" },
			{ "炸弹",		"Bomb",			"💣" },
			{ "便便",		"Poop",			"💩" },
			{ "月亮",		"Moon",			"🌃" },
			{ "太阳",		"Sun",			"🌞" },
			{ "拥抱",		"Hug",			"🤗" },
			{ "握手",		"Shake",		"🤝" },
			{ "胜利",		"Victory",		"✌" },
			{ "抱拳",		"Salute",		"🙏" },
			{ "拳头",		"Fist",			"👊" },
			{ "跳跳",		"Waddle",		"💃" },
			{ "发抖",		"Tremble",		"🙇" },
			{ "怄火",		"Aaagh!",		"😡" },
			{ "转圈",		"Twirl",		"🕺" },
			{ "蜡烛",		"Candle",		"🕯️" },
//			{ "勾引",		"Beckon",		""},
//			{ "嘿哈",		"Hey",			"" },
//			{ "机智",		"Smart",		"" },
//			{ "抠鼻",		"DigNose",		"" },
//			{ "可怜",		"Whimper",		"" },
			{ "皇冠",       null,           "👑" },
			{ "鬼魂",       null,           "👻" },
			{ "快哭了",		"Puling",		"😔" },
//			{ "左哼哼",		"Bah！L",		"" },
//			{ "右哼哼",		"Bah！R",		"" },
			{ "破涕为笑",	"Lol",			"😂" },
	};
}
